obj-$(CONFIG_KEYSTONE_ENCLAVE) += keystone.o keystone-rtld.o keystone-page.o
obj-$(CONFIG_SBI_CONSOLE) += sbi-con.o
obj-$(CONFIG_SBI_DISK) += sbi-disk.o
obj-$(CONFIG_GENERIC_BLKDEV) += generic-blkdev.o
obj-$(CONFIG_ICENET) += icenet.o

clean:
